spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    port: 1025
    username: null
    password: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  application:
    name: bedrock
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5431/bedrock_demo
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # for dev only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        org.hibernate.envers.audit_table_suffix: _AUD
        org.hibernate.envers.default_schema: audit
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bedrock:
  auditing:
    flow:
      async-enabled: false
    entity:
      enabled: true
      strategy: envers
  security:
    enabled: true
    # authorization:
    #   public-paths:
    #     - "/api/audit/**"
    permit-all:
      - "/v3/api-docs"
      - "/v3/api-docs/**"
      - "/swagger-ui"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/actuator/**"
      - "/api/v1/auth/**"
      - "/api/audit/**"
      - "/api/v1/student/greet"
  logging:
    enabled: true
    level: INFO
    file:
      enabled: true
      path: "./logs"
      name: "bedrock-app.log"
  monitoring:
    enabled: true
    implementation: prometheus

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.datamate.bedrock: DEBUG